//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Johny.Project.Model.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class VM_R_Base
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string EnglishName { get; set; }
        public string Code { get; set; }
        public string GroupCode { get; set; }
        public string CategoryCode { get; set; }
        public string GroupCategoryCode { get; set; }
        public string ABCType { get; set; }
        public string ModelCode { get; set; }
        public Nullable<int> OwnerDeptID { get; set; }
        public Nullable<int> InUseDeptID { get; set; }
        public string ResourceStatusCode { get; set; }
        public string GlobalRegionCode { get; set; }
        public string Manufacturer { get; set; }
        public Nullable<System.DateTime> PoductionDate { get; set; }
        public string PoductionCode { get; set; }
        public string Supplier { get; set; }
        public Nullable<System.DateTime> DatePurchased { get; set; }
        public string SallingCode { get; set; }
        public Nullable<decimal> Value { get; set; }
        public Nullable<decimal> NetValue { get; set; }
        public string DeliveType { get; set; }
        public Nullable<decimal> DeliveValue { get; set; }
        public string DeliveUnit { get; set; }
        public string OldCode { get; set; }
        public string DataRole { get; set; }
        public Nullable<int> Status { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedTime { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedTime { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public string LargeLandMachineTypeCode { get; set; }
        public string CountryOfProduction { get; set; }
        public string CompanyTypeCode { get; set; }
        public string FNCTypeCode { get; set; }
        public string OldCompanyTypeCode { get; set; }
        public string remark { get; set; }
    }
}
